<?php

require_once dirname(__FILE__) . '/../Android.php';

/**
 * Test class for Android.
 * Generated by PHPUnit on 2011-08-27 at 08:10:41.
 */
class AndroidTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Android
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Android;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testRpc().
     */
    public function testRpc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
